language: python
python:
  - "3.6"
install:
  - pip install cfn-lint taskcat awscli

git:
    submodules: false
before_install:
    # DELETE ME
    - my_ip=`curl ipinfo.io | jq .ip`;eval my_ip=${my_ip[i]}
    - my_ip="$my_ip/32"
    - export BASE_IP=$my_ip

    - sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
    - git submodule update --init --recursive
    - git checkout .gitmodules

script:
  - make lint
  - make test

deploy:
  provider: script
  script: make sync BRANCH=$TRAVIS_BRANCH
  on:
    branch:
      - master
      - develop
